exports.STATUS = {
  RECEIVED: 'Received',
  INTERVIEWING: 'Interviewing',
  OFFERED: 'Offered',
  AWAITING_CONDITIONS: 'Conditions pending',
  RECRUITED: 'Recruited',
  APPLICATION_WITHDRAWN: 'Application withdrawn',
  REJECTED: 'Rejected',
  OFFER_WITHDRAWN: 'Offer withdrawn',
  DECLINED: 'Declined',
  CONDITIONS_NOT_MET: 'Conditions not met',
  DEFERRED: 'Deferred',
}

exports.EVENTS = {
  SUBMITTED: 'Application submitted',
  INTERVIEW_SET_UP: 'Interview set up',
  INTERVIEW_CHANGED: 'Interview changed',
  INTERVIEW_CANCELLED: 'Interview cancelled',
  OFFER_MADE: 'Offer made',
  OFFER_CHANGED: 'Offer changed',
  OFFER_ACCEPTED: 'Offer accepted',
  OFFER_DECLINED: 'Offer declined',
  OFFER_WITHDRAWN: 'Offer withdrawn',
  OFFER_DEFERRED: 'Offer deferred',
  OFFER_RECONFIRMED: 'Offer reconfirmed',
  CONDITIONS_MET: 'Conditions marked as met',
  CONDITIONS_NOT_MET: 'Conditions marked as not met',
  REJECTED: 'Application rejected',
  FEEDBACK_SENT: 'Feedback sent',
  WITHDRAWN: 'Application withdrawn',
  OFFER_CONDITIONS_UPDATED: 'Status of conditions updated',
  NOTE_ADDED: 'Note added',
}
